---
title: "Running from Trex"
author: "Nick Borcherding"
date: "7/6/2021"
output: html_document
---

```{r}
library(stringr)
library(stringdist)
library(amap)
library(dplyr)
library(muxViz)
reference <- read.delim("~/Documents/GitHub/Trex/data/aa_props.tsv")
igraph <- runTrex(tmp)
```

```{r}
N <- simplify(igraph)
eigen <- spectrum(N, 
                 which = 20, 
                 algorithm = "arpack")
#ProjectionMatrix <- magic....(not done yet)
#Making essientially a pca out of the sparse matrix
Trex <- CreateDimReducObject(
    embeddings = ProjectionMatrix,
    loadings = ProjectionMatrix,
    projected = ProjectionMatrix,
    assay = "RNA",
    stdev = rep(0, ncol(ProjectionMatrix)),
    key = NULL,
    jackstraw = NULL,
    misc = list()
  )
tmp@reductions[["Trex"]] <- Trex


wnn  <- FindMultiModalNeighbors(
  tmp, 
  reduction.list = list("pca", "Trex"), 
  dims.list = list(1:30, 1:25), 
  modality.weight.name = "RNA.weight"
)

plot_multiplex(g.list, layer.colors = viridis::viridis_pal(option = "H")(4))
```

